### ISSUE TITLE
Jumps to the Japanese page when clicks an item in the header menu in the English page

### ISSUE THREAD

**Issue by koher** [tryswift-tokyo-after-talks/tryswift-tokyo-after-talks.github.io#17]
## How to reproduce

1. Open https://tryswift-tokyo-after-talks.github.io/en/
2. Click "TIMETABLE" in the header menu

Then you can see the timetable in the Japanese page.

**Comment by takasek** [comment]
Oh, I reproduced it!

**Comment by takasek** [comment]
@koher thank you for reporting!
